# Generated by Django 4.1.3 on 2022-11-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('role', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Calling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('injures', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('called', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called', to='call.person')),
                ('workerIds', models.ManyToManyField(to='call.person')),
            ],
        ),
    ]
