# Generated by Django 4.1.3 on 2022-12-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('injures', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=20)),
                ('coordinateX', models.FloatField(default=0.0)),
                ('coordinateY', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'call',
                'verbose_name_plural': 'calls',
                'db_table': 'call',
            },
        ),
        migrations.CreateModel(
            name='CallToPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.call')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Guest', 'Guest'), ('Worker', 'Worker')], default='Guest', max_length=6)),
                ('call', models.ManyToManyField(blank=True, null=True, through='call.CallToPerson', to='call.call')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'person',
                'ordering': ('surname',),
            },
        ),
        migrations.AddField(
            model_name='calltoperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.person'),
        ),
    ]
