# Generated by Django 4.1.3 on 2022-11-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('injury', models.CharField(choices=[('Да', 'Yes'), ('Нет', 'No'), ('Не знаю', 'Unknown')], max_length=7)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Worker', 'Worker'), ('Admin', 'Admin')], max_length=6),
        ),
        migrations.DeleteModel(
            name='Calling',
        ),
        migrations.AddField(
            model_name='call',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='call.person'),
        ),
        migrations.AddField(
            model_name='call',
            name='workers',
            field=models.ManyToManyField(to='call.person'),
        ),
    ]
