# Generated by Django 4.1.3 on 2022-12-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='injures',
            field=models.CharField(choices=[('Да', 'Yes'), ('Нет', 'No'), ('Нет инфорамции', 'Unknown')], max_length=20),
        ),
    ]
