# Generated by Django 4.1.3 on 2022-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='call',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons', through='call.CallToPerson', to='call.call'),
        ),
    ]
