# Generated by Django 4.1.3 on 2022-12-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoperson',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.call'),
        ),
        migrations.AlterField(
            model_name='calltoperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.person'),
        ),
    ]
