# Generated by Django 4.1.3 on 2022-12-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltoperson',
            options={'verbose_name': 'call_to_person', 'verbose_name_plural': 'calls_to_persons'},
        ),
        migrations.AlterField(
            model_name='call',
            name='injures',
            field=models.CharField(choices=[('Да', 'Yes'), ('Нет', 'No'), ('Нет инфорамции', 'Unknown')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='calltoperson',
            unique_together={('person', 'call')},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'surname', 'patronymic')},
        ),
        migrations.AlterModelTable(
            name='calltoperson',
            table='call_to_person',
        ),
    ]
