# Generated by Django 4.1.3 on 2022-11-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_call_alter_person_role_delete_calling_call_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='injury',
            new_name='injures',
        ),
    ]
