# Generated by Django 4.1.3 on 2022-11-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_rename_injury_call_injures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
