# Generated by Django 4.1.3 on 2022-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_remove_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Worker', 'Worker')], default='Guest', max_length=6),
        ),
    ]
