# Generated by Django 4.1.3 on 2022-11-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_person_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='workers',
        ),
    ]
