# Generated by Django 4.1.3 on 2022-11-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_remove_call_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='call',
            name='longitude',
        ),
    ]
