# Generated by Django 4.1.3 on 2022-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0007_remove_call_latitude_remove_call_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='injures',
            field=models.CharField(choices=[('Да', 'Yes'), ('Нет', 'No'), ('Нет информации', 'Unknown')], max_length=20),
        ),
    ]
