# Generated by Django 4.1.3 on 2022-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0008_alter_call_injures'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, to='call.person'),
        ),
    ]
