# Generated by Django 4.1.3 on 2022-12-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0009_call_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='workers',
        ),
        migrations.AddField(
            model_name='call',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='call',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='person',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call', to='call.call'),
        ),
    ]
