# Generated by Django 4.1.3 on 2022-12-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0010_remove_call_workers_call_latitude_call_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='latitude',
            new_name='coordinateX',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='longitude',
            new_name='coordinateY',
        ),
    ]
